### PR TITLE
Add delete vid files

### PR DESCRIPTION
**Pull request by cit280superepicness**
Is functional but still have some stuff related to device mac to add and test what i added for adding the time to the database

### CODE REVIEW

**Comment by jrmullen** [comment]
If you feel confident that this is working as intended we can merge. Otherwise please give steps to QA.

**Comment by cit280superepicness** [comment]
Will finish on testing the time stuff and also I will finish adding the
code for the device mac and test it tonight/tomorrow. QAing the code to
insert video files into the DB is quite complicated and a bit difficult
without an understanding of the code and playing around with throwing
multiple video files into the c:/ftp/video folder on the server. Due to
this, I will try to write the QA steps for this myself after I test if that
is alright.

**Comment by jrmullen** [comment]
if it works i dont think we need to qa it. It's probably not worth the time. it won't even be seen in our presentation

**Comment by cit280superepicness** [comment]
Sure about QA. We can still demo it in our presentation though. Our
professor asked about it at our last presentation so.

**Comment by cit280superepicness** [comment]
> if it works i dont think we need to qa it. It's probably not worth the time. it won't even be seen in our presentation

Sure about QA. We can still demo it in our presentation though. Our
professor asked about it at our last presentation so.

**Comment by cit280superepicness** [comment]
I very very thoroughly tested this. I have it running off the server right now.

**Pull request merged**
